# Generated by Django 2.2.9 on 2020-01-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_formname_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='formname',
            name='portfolio_site',
            field=models.URLField(blank=True),
        ),
    ]
