# Generated by Django 2.2.9 on 2020-01-15 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_formname_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='password',
        ),
    ]
