# Generated by Django 2.2.9 on 2020-01-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='picture',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
